services:
  - type: web
    name: ai-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PUSHOVER_TOKEN
        sync: false
      - key: PUSHOVER_USER_KEY
        sync: false
      - key: USE_EVALUATOR
        value: false
      - key: CORS_ORIGINS
        value: https://ai-agent-frontend.onrender.com  # Match frontend URL
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
  - type: web
    name: ai-agent-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install
    startCommand: cd frontend && node server.js
    envVars:
      - key: VITE_API_URL
        value: https://ai-agent.onrender.com/chat  # Point to backend